name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Configure Git for GitHub Pages deploy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.GH_TOKEN2 }}@github.com/rodrigohisashi/studies-wiki.git

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --remote-name origin --remote-branch gh-pages
